"""add idempotency key to usage events

Revision ID: 10bb7eb21c52
Revises: 43dca0c47b44
Create Date: 2026-08-10 16:47:28.652895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bb7eb21c52'
down_revision: Union[str, Sequence[str], None] = '43dca0c47b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "usage_events",
        sa.Column(
            "idempotency_key",
            sa.String(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE usage_events "
        "SET idempotency_key = 'legacy-' || id::text "
        "WHERE idempotency_key IS NULL"
    )

    op.alter_column(
        "usage_events",
        "idempotency_key",
        nullable=False,
    )

    op.create_unique_constraint(
        "uq_usage_events_idempotency_key",
        "usage_events",
        ["idempotency_key"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_events', type_='unique')
    op.drop_column('usage_events', 'idempotency_key')
    # ### end Alembic commands ###
