"""add billing period to invoices

Revision ID: 4c4dce7abd0f
Revises: 8b0e3e7d8039
Create Date: 2026-08-11 11:25:03.465194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4dce7abd0f'
down_revision: Union[str, Sequence[str], None] = '8b0e3e7d8039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'invoices',
        sa.Column('period_start', sa.DateTime(), nullable=True)
    )

    op.add_column(
        'invoices',
        sa.Column('period_end', sa.DateTime(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'period_end')
    op.drop_column('invoices', 'period_start')
    # ### end Alembic commands ###
